project:
  type: website
  output-dir: docs

website:
  title: FDA Blog
  site-url: https://saintrod.github.io/fda-blog/
  navbar:
    search: true
    left:
      - text: Posts
        href: blog.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/santiagorodriguez91/
      - icon: github
        href: https://github.com/SaintRod/
      - icon: gitlab
        href: https://gitlab.com/hail_hydra
  page-footer: 
    background: dark 
    left: Copyright 2024, Santiago Rodriguez
    right: Built with Quarto

format:
  html:
    theme: cosmo
    css: styles.css

