---
title: 'A Novel Approach to Define the Peak Hours of Consumption for Individual Customers and Groups of Customers Using Functional Data Analysis'
date: '2022-09-01'
categories: ['Residential', 'Research']
description: 'Research about functional data anlaysis performed at Consumers Energy'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

The work should be visible below.
If it isn't please clink this ([link](https://rpubs.com/kaladin_stormblessed/onpeak_fda)).

# Abstract

The following text was obtained from the publication.

> A common analysis in utilities is the use of meter read data to define peak hours of consumption. This paper proposes a novel approach using functional data analysis (FDA) to define the peak hours of consumption for individual customers and groups of customers. Through functional data analysis, smooth, differentiable curves are fitted to an individual customer’s meter read data. Then, the individual on-peak times are aggregated to define on-peak hours for a group of customers, such as for all residential customers.

> The individual customer on-peak hours are proposed as the times of day where the velocity or the rate of change is greatest or least, respectively. The group on-peak hours are determined by two different methods; the first by assessing the distributions of the start and end aggregated individual on-peak windows and the second via an unsupervised statistical learning procedure.

::: {=html}
<iframe src="https://rpubs.com/kaladin_stormblessed/onpeak_fda" width="100%" height="700px"></iframe>
:::